
services:
  app:
    build: .
    container_name: BMS_app
    networks:
      - banking-net
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bankdb
      SPRING_DATASOURCE_USERNAME: your username
      SPRING_DATASOURCE_PASSWORD: your password
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:17
    container_name: banking_postgres
    networks:
      - banking-net
    restart: always
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: banking_redis
    networks:
      - banking-net
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: your default email
      PGADMIN_DEFAULT_PASSWORD: your password
    ports:
      - "5051:80"  # access at localhost:5051
    depends_on:
      - db
    networks:
      - banking-net
volumes:
  postgres_data:
  redis_data:

networks:
  banking-net:
    driver: bridge
